flask:
  secret_key: 'your_secret_key'
  debug: false
  testing: true
  CORS_ORIGINS: '*'
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:yy0908..@127.0.0.1/zyf_260123'
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  SQLALCHEMY_ECHO: false
  SQLALCHEMY_POOL_SIZE: 20
  SQLALCHEMY_POOL_TIMEOUT: 90
  SQLALCHEMY_POOL_RECYCLE: 3600
  SQLALCHEMY_MAX_OVERFLOW: 30
  SQLALCHEMY_POOL_PRE_PING: true
  REDIS_URL: "redis://127.0.0.1?db=1"


log:
  level: DEBUG
  filename: logs/ruoyi.log
  filesize: 100MB
  filenum: 10
  formatter:
    fmt: '%(asctime)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'
